### ISSUE TITLE
Getting Errors When Importing Project to Intellij Idea

### ISSUE THREAD

**Issue by SanjaySaluth** [wsong-nj/EHBDroid#4]
Hi, 

Operating System : Ubuntu 14.04
Intellij Idea : Community 2017

I have imported the project in Intellij Idea, but its showing too much errors, when trying to run Main file.

Information:java: Errors occurred while compiling module 'EHBDroid,ehb'
Information:javac 1.8.0_141 was used to compile java sources
Information:30/1/18 8:12 AM - Compilation completed with 72 errors and 3 warnings in 2s 703ms
/home/sanjaysaluth/pro/EHB/EHBDroid/EHBDroid/src/com/app/test/Constants.java
Error:(7, 40) java: package ehb.instrumentation.codecoverage does not exist
Error:(113, 62) java: cannot find symbol
  symbol:   class CoverageToolkit
  location: class com.app.test.Constants
/home/sanjaysaluth/pro/EHB/EHBDroid/EHBDroid/src/com/app/test/methodModifier/ClinitForActivityModifier.java
Error:(21, 18) java: package ehb.global does not exist
Error:(55, 54) java: cannot find symbol
  symbol: variable Global
/home/sanjaysaluth/pro/EHB/EHBDroid/EHBDroid/src/com/app/test/methodCoverage/MethodCoverageFieldInstrumenter.java
Error:(22, 18) java: package ehb.global does not exist
Error:(23, 27) java: package ehb.instrumentation does not exist
Error:(25, 78) java: cannot find symbol
  symbol: class IInstrumenter
Error:(33, 9) java: method does not override or implement a method from a supertype
Error:(45, 50) java: cannot find symbol
  symbol:   variable Global
  location: class com.app.test.methodCoverage.MethodCoverageFieldInstrumenter
/home/sanjaysaluth/pro/EHB/EHBDroid/EHBDroid/src/com/app/test/Main.java
Error:(9, 20) java: package ehb.analysis does not exist
Error:(10, 18) java: package ehb.global does not exist
Error:(11, 24) java: package ehb.xml.manifest does not exist
Error:(12, 24) java: package ehb.xml.manifest does not exist
Error:(13, 24) java: package ehb.xml.resource does not exist
Error:(14, 24) java: package ehb.xml.resource does not exist
Error:(53, 17) java: cannot find symbol
  symbol:   class ProcessManifest
  location: class com.app.test.Main
Error:(53, 50) java: cannot find symbol
  symbol:   class ProcessManifest
  location: class com.app.test.Main
Error:(57, 17) java: cannot find symbol
  symbol:   class ProcessResource
  location: class com.app.test.Main
Error:(57, 55) java: cannot find symbol
  symbol:   class ProcessResource
  location: class com.app.test.Main
Error:(59, 22) java: cannot find symbol
  symbol:   class ResourceAttributes
  location: class com.app.test.Main
Error:(60, 17) java: cannot find symbol
  symbol:   class CallBackGenerator
  location: class com.app.test.Main
Error:(60, 51) java: cannot find symbol
  symbol:   class CallBackGenerator
  location: class com.app.test.Main
Error:(66, 17) java: cannot find symbol
  symbol:   class CallGraphBuilder
  location: class com.app.test.Main
Error:(66, 44) java: cannot find symbol
  symbol:   class CallGraphBuilder
  location: class com.app.test.Main
Error:(81, 48) java: cannot find symbol
  symbol:   variable apkPath
  location: class com.app.test.Main
Error:(90, 48) java: cannot find symbol
  symbol:   variable CallGraphBuilder
  location: class com.app.test.Main
Error:(93, 43) java: cannot find symbol
  symbol:   variable CallGraphBuilder
  location: class com.app.test.Main
Error:(96, 41) java: cannot find symbol
  symbol:   variable CallGraphBuilder
  location: class com.app.test.Main
Error:(106, 57) java: cannot find symbol
  symbol:   variable Global
  location: class com.app.test.Main
Error:(108, 65) java: cannot find symbol
  symbol:   variable Global
  location: class com.app.test.Main
Error:(109, 60) java: cannot find symbol
  symbol:   variable Global
  location: class com.app.test.Main
Error:(111, 38) java: cannot find symbol
  symbol:   variable Global
  location: class com.app.test.Main
Error:(112, 81) java: cannot find symbol
  symbol:   variable Global
  location: class com.app.test.Main
Error:(113, 40) java: cannot find symbol
  symbol:   variable Global
  location: class com.app.test.Main
Error:(125, 41) java: cannot find symbol
  symbol:   variable Global
  location: class com.app.test.Main
Error:(128, 60) java: cannot find symbol
  symbol:   variable Global
  location: class com.app.test.Main
Error:(162, 41) java: cannot find symbol
  symbol:   variable Global
  location: class com.app.test.Main
Error:(163, 41) java: cannot find symbol
  symbol:   variable Global
  location: class com.app.test.Main
Error:(164, 41) java: cannot find symbol
  symbol:   variable Global
  location: class com.app.test.Main
Error:(165, 41) java: cannot find symbol
  symbol:   variable Global
  location: class com.app.test.Main
/home/sanjaysaluth/pro/EHB/EHBDroid/EHBDroid/src/com/app/test/methodCoverage/MethodCoverageStmtsInstrumenter.java
Error:(24, 27) java: package ehb.instrumentation does not exist
Error:(29, 57) java: cannot find symbol
  symbol: class IInstrumenter
Error:(125, 9) java: method does not override or implement a method from a supertype
/home/sanjaysaluth/pro/EHB/EHBDroid/EHBDroid/src/com/app/test/data/Main.java
Error:(7, 20) java: package ehb.analysis does not exist
Error:(31, 17) java: cannot find symbol
  symbol:   class CallGraphBuilder
  location: class com.app.test.data.Main
Error:(31, 44) java: cannot find symbol
  symbol:   class CallGraphBuilder
  location: class com.app.test.data.Main
/home/sanjaysaluth/pro/EHB/EHBDroid/EHBDroid/src/com/app/test/methodBuilder/Clinit.java
Error:(14, 18) java: package ehb.global does not exist
Error:(47, 55) java: cannot find symbol
  symbol:   variable Global
  location: class com.app.test.methodBuilder.Clinit
/home/sanjaysaluth/pro/EHB/EHBDroid/EHBDroid/src/com/app/test/AppBodyTransformer.java
Error:(9, 20) java: package ehb.analysis does not exist
Error:(10, 20) java: package ehb.analysis does not exist
Error:(18, 18) java: package ehb.global does not exist
Error:(19, 18) java: package ehb.global does not exist
Error:(20, 27) java: package ehb.instrumentation does not exist
Error:(21, 27) java: package ehb.instrumentation does not exist
Error:(22, 27) java: package ehb.instrumentation does not exist
Error:(23, 27) java: package ehb.instrumentation does not exist
Error:(24, 40) java: package ehb.instrumentation.codecoverage does not exist
Error:(25, 40) java: package ehb.instrumentation.codecoverage does not exist
Error:(26, 16) java: package ehb.sign does not exist
Error:(43, 68) java: cannot find symbol
  symbol: class GlobalHost
Error:(45, 78) java: cannot find symbol
  symbol:   variable Global
  location: class com.app.test.AppBodyTransformer
Error:(72, 13) java: cannot find symbol
  symbol:   class SignCheckRemover
  location: class com.app.test.AppBodyTransformer
Error:(76, 13) java: cannot find symbol
  symbol:   class ApplicationClassInstrumenter
  location: class com.app.test.AppBodyTransformer
Error:(76, 42) java: cannot find symbol
  symbol:   variable CallGraphBuilder
  location: class com.app.test.AppBodyTransformer
Error:(80, 13) java: cannot find symbol
  symbol:   class FieldInstrumenter
  location: class com.app.test.AppBodyTransformer
Error:(80, 31) java: cannot find symbol
  symbol:   variable Global
  location: class com.app.test.AppBodyTransformer
Error:(93, 13) java: cannot find symbol
  symbol:   class ActivityInstrumenter
  location: class com.app.test.AppBodyTransformer
Error:(97, 13) java: cannot find symbol
  symbol:   class BodyInstrumenter
  location: class com.app.test.AppBodyTransformer
Error:(101, 13) java: cannot find symbol
  symbol:   class CoverageClassInstrumenter
  location: class com.app.test.AppBodyTransformer
Error:(102, 13) java: cannot find symbol
  symbol:   class CoverageBodyInstrumenter
  location: class com.app.test.AppBodyTransformer
Error:(108, 58) java: package CoverageClassInstrumenter does not exist
Error:(175, 5) java: method does not override or implement a method from a supertype
/home/sanjaysaluth/pro/EHB/EHBDroid/EHBDroid/src/com/app/test/event/UIEventHandler.java
Warning:(484, 49) java: getPreferenceScreen() in android.preference.PreferenceActivity has been deprecated
Warning:(542, 43) java: non-varargs call of varargs method with inexact argument type for last parameter;
  cast to java.lang.Object for a varargs call
  cast to java.lang.Object[] for a non-varargs call and to suppress this warning
/home/sanjaysaluth/pro/EHB/EHBDroid/EHBDroid/src/com/app/test/Util.java
Warning:(125, 45) java: getPreferenceScreen() in android.preference.PreferenceActivity has been deprecated
/home/sanjaysaluth/pro/EHB/EHBDroid/EHBDroid/src/com/app/test/event/InterAppEventHandler.java
Information:java: Some input files use unchecked or unsafe operations.
Information:java: Recompile with -Xlint:unchecked for details.

Any Idea please?

**Comment by Xiangxingqian** [comment]
Hi SanjaySaluth,

Can you try to import EHBDroid as an eclipse project in Intellij IDEA?

Start Intellij IDEA -> Import Project -> select EHBDroid repo -> Import project from external model -> select Eclipse -> next...-> finish.

**Comment by SanjaySaluth** [comment]
Hi Xiangxingqian, 

Its working perfectly now.
Thanks
